InsuranceApp/urls.py
from . import views

from django.urls import path

app_name = "InsuranceApp"

urlpatterns = [
    path("", views.ServiceListView.as_view(), name="index"),
    path("login", views.LoginView.as_view(), name="login"),
    path("register", views.RegisterView.as_view(), name="register"),
    path("logout", views.LogoutView.as_view(), name="logout"),
    path("profile", views.UpdateUserView.as_view(), name="profile"),
    path("services", views.CompanyServicesView.as_view(), name="services"),
    path("create_service", views.CreateServiceView.as_view(), name="create_service"),
    path("update_service/<int:service_id>", views.UpdateServiceView.as_view(), name="update_service"),
    path("delete_service/<int:service_id>", views.DeleteServiceView.as_view(), name="delete_service"),
    path("services/<int:service_id>", views.ServiceView.as_view(), name="service"),
    path("responses", views.ResponsesView.as_view(), name="responses")
]

InsuranceExchange/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("InsuranceApp.urls")),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")))
]
urlpatterns += staticfiles_urlpatterns()

InsuranceApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField


class Company(AbstractUser):
    """Users within the Django authentication system are represented by this model"""
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=255, unique=True)
    phone = models.CharField(max_length=20)
    description = models.TextField(null=True)
    password = models.CharField(max_length=200)
    create_date = models.DateField(auto_now_add=True)
    username = models.CharField(max_length=30, unique=False)

    # Overridden attribute for Django authentication system, because 'username' field does not exist
    USERNAME_FIELD = "email"

    # Overridden attribute to avoid collisions with 'USERNAME_FIELD'
    REQUIRED_FIELDS = ["name", "phone", "password"]


class InsuranceType(models.Model):
    """Insurance type model that represent 'name' and 'risks' of insurance"""
    name = models.CharField(max_length=200)
    risks = ArrayField(models.CharField(max_length=30))


class ValidityType(models.Model):
    """Validity type model that represent 'name' and 'time' of insurance"""
    name = models.CharField(max_length=20)
    time = models.FloatField()


class Service(models.Model):
    """Service model for represent service by 'company'"""
    title = models.CharField(max_length=200)
    description = models.TextField(null=True)
    type = models.ForeignKey(InsuranceType, on_delete=models.CASCADE)
    validity = models.ForeignKey(ValidityType, on_delete=models.CASCADE)
    coverage_amount = models.FloatField()
    price = models.FloatField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)


class Response(models.Model):
    """Response model for represent response by client for 'company'"""
    full_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=20)
    birth_date = models.DateField()
    response_date = models.DateField(auto_now_add=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

InsuranceApp/forms.py
from django import forms
from datetime import date
from django.contrib.auth.forms import UserCreationForm

from .models import Company, Service, Response, ValidityType, InsuranceType


class RegisterForm(UserCreationForm):
    """A form that creates a user, with no privileges, from the given username and password"""
    name = forms.CharField(max_length=200)
    email = forms.EmailField(max_length=255, widget=forms.EmailInput)
    phone = forms.CharField(max_length=20)
    description = forms.Textarea()

    class Meta:
        """Configuration class for auto-generated fields and form customizations"""
        model = Company
        fields = ("name", "email", "phone", "description", "password1", "password2")

    def save(self, commit=True):
        """Save this form's self.instance object if commit=True. Otherwise, add
        a email fields to the model and save. Return the model instance."""
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class UpdateUserForm(forms.ModelForm):
    """A form that updates existing user"""
    name = forms.CharField(max_length=200)
    email = forms.EmailField(max_length=255, widget=forms.EmailInput, disabled=True)
    phone = forms.CharField(max_length=20)
    description = forms.Textarea()

    class Meta:
        """Configuration class for auto-generated fields and form customizations"""
        model = Company
        fields = ("name", "email", "phone", "description")


class ServiceForm(forms.ModelForm):
    """A form that create and update service object"""
    title = forms.CharField(max_length=200)
    price = forms.FloatField()
    coverage_amount = forms.FloatField()
    description = forms.Textarea()
    type = forms.ChoiceField(widget=forms.Select, choices=InsuranceType.objects.values_list("pk", "name"))
    validity = forms.ChoiceField(widget=forms.Select, choices=ValidityType.objects.values_list("pk", "name"))

    class Meta:
        """Configuration class for auto-generated fields and form customizations"""
        model = Service
        fields = ("title", "description", "coverage_amount", "price", "type", "validity")

    def clean_type(self):
        """Method for cleaning data from 'type' field. Return 'InsuranceType' object by primary key."""
        return InsuranceType.objects.get(pk=self.cleaned_data["type"])

    def clean_validity(self):
        """Method for cleaning data from 'validity' field. Return 'ValidityType' object by primary key."""
        return ValidityType.objects.get(pk=self.cleaned_data["validity"])


class ResponseForm(forms.ModelForm):
    """A form that create response object"""
    full_name = forms.CharField(max_length=200)
    email = forms.EmailField(widget=forms.EmailInput, max_length=200)
    phone = forms.CharField(max_length=12)
    birth_date = forms.DateField(initial=date.today())

    class Meta:
        """Configuration class for auto-generated fields and form customizations"""
        model = Response
        fields = ("full_name", "email", "phone", "birth_date")

InsuranceApp/views.py
from .tasks import send_response_notification
from .services import search_by_services, get_services_by_company
from .forms import RegisterForm, UpdateUserForm, ServiceForm, ResponseForm
from .models import Company, Service, Response, InsuranceType, ValidityType

from redis import StrictRedis

from django.conf import settings
from django.shortcuts import redirect

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from django.views.generic import View
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView

redis = StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=0)


class ServiceListView(ListView):
    """Render 'Service' list of objects, set by 'self.queryset'"""
    paginate_by = 10
    ordering = "title"
    template_name = "index.html"

    def get_queryset(self):
        return search_by_services(self.request)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            "found": self.get_queryset().count(),
            "sorting": (
                ("title", "Title: A to Z"),
                ("-title", "Title: Z to A"),
                ("price", "Price: Low to High"),
                ("-price", "Price: High to Low")
            ),
            "companies": Company.objects.values_list("pk", "name"),
            "types": InsuranceType.objects.values_list("pk", "name"),
            "validities": ValidityType.objects.values_list("pk", "name")
        })

        return context


class RegisterView(SuccessMessageMixin, CreateView):
    """View for creating a new 'Company' object, with a response rendered by a template"""
    form_class = RegisterForm
    success_url = "/"
    template_name = "company/register.html"
    success_message = "Registration successful"


class LoginView(SuccessMessageMixin, FormView):
    """A view for user login and rendering a template response"""
    form_class = AuthenticationForm
    success_url = "/"
    template_name = "company/login.html"
    success_message = "You are now logged in"

    def form_valid(self, form):
        user: Company = authenticate(username=form.cleaned_data.get("username"),
                                     password=form.cleaned_data.get("password"))
        if user is not None:
            login(self.request, user)

        return super().form_valid(form)


class LogoutView(LoginRequiredMixin, SuccessMessageMixin, View):
    """A view for user logout from system, implemented only 'GET' function"""
    login_url = "/login"
    success_message = "You have successfully logged out"

    def get(self, request):
        logout(request)
        return redirect("InsuranceApp:index")


class UpdateUserView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """View for updating an 'Company' object, with a response rendered by a template"""
    model = Company
    form_class = UpdateUserForm
    success_url = "/"
    login_url = "/login"
    template_name = "company/update.html"
    success_message = "Profile successful updated"

    def get_object(self, queryset=None):
        return self.request.user


class CompanyServicesView(LoginRequiredMixin, ListView):
    """Render 'Service' list of objects, set by 'get_queryset' function"""
    paginate_by = 10
    ordering = "title"
    login_url = "/login"
    template_name = "services/services.html"

    def get_queryset(self):
        return get_services_by_company(self.request.user.id)


class CreateServiceView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """View for creating a new 'Service' object, with a response rendered by a template"""
    form_class = ServiceForm
    login_url = "/login"
    success_url = "/services"
    template_name = "services/create.html"
    success_message = "Service successful created"

    def form_valid(self, form):
        service: Service = form.save(commit=False)
        service.company = self.request.user
        service.save()

        redis.set(f"services/{service.id}", 0)
        return super().form_valid(form)


class UpdateServiceView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """View for updating an 'Service' object, with a response rendered by a template"""
    model = Service
    form_class = ServiceForm
    login_url = "/login"
    success_url = "/services"
    pk_url_kwarg = "service_id"
    template_name = "services/update.html"
    success_message = "Service successful updated"


class DeleteServiceView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    """View for deleting an 'Service' object, with a response rendered by a template"""
    model = Service
    login_url = "/login"
    pk_url_kwarg = "service_id"
    success_url = "/services"
    success_message = "Service successful deleted"

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def form_valid(self, form):
        service: Service = form.save()

        redis.delete(f"services/{service.id}")
        return super().form_valid(form)


class ServiceView(SuccessMessageMixin, DetailView, CreateView):
    """Combine class-based view for retrieve 'Service' and return form, with a response rendered by a template"""
    model = Service
    form_class = ResponseForm
    success_url = "/"
    pk_url_kwarg = "service_id"
    template_name = "service.html"
    context_object_name = "service"

    def form_valid(self, form):
        response: Response = form.save(commit=False)
        response.service = Service.objects.get(pk=self.object.id)
        response.company = response.service.company
        response.save()

        send_response_notification.delay({
            "email": response.email,
            "phone": response.phone,
            "full_name": response.full_name,
            "company": response.company.email,
            "service": response.service.title,
            "response_date": response.response_date,
        })

        return super().form_valid(form)

    def get_success_message(self, cleaned_data):
        return f"Response to {self.object.company.name} successful created"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        redis.incr(f"services/{self.object.id}")

        if self.object.company.id == self.request.user.id:
            context["views"] = int(redis.get(f"services/{self.object.id}"))

        return context


class ResponsesView(LoginRequiredMixin, ListView):
    """Render 'Response' list of objects, set by 'get_queryset' function"""
    paginate_by = 10
    ordering = "full_name"
    login_url = "/login"
    template_name = "responses.html"

    def get_queryset(self):
        return Response.objects.filter(company=self.request.user)

InsuranceApp/templates/_header.html
{% load static %}
<header>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="navbar-brand" href="{% url 'InsuranceApp:index' %}">
                    <img src="{% static 'img/logo.svg' %}" width="30" height="30" class="d-inline-block align-top"
                         alt="logo">
                    Insurance Exchange
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'InsuranceApp:services' %}">Services</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'InsuranceApp:responses' %}">Responses</a>
            </li>
            {% endif %}
        </ul>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="{% url 'InsuranceApp:profile' %}">{{ user.name }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'InsuranceApp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'InsuranceApp:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'InsuranceApp:login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Messages -->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    <!-- Optional Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
</header>

InsuranceApp/templates/index.html
<!DOCTYPE html>
<!-- Header -->
{% include "_header.html" %}
{% load tags %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Insurance Exchange</title>
</head>
<body>
<div class="container py-5">
    <!-- Search -->
    <form class="form-inline" method="GET">
        <label class="sr-only" for="query">Search</label>
        <input type="text" class="col-8 input-group mb-2 mr-sm-2" id="query" name="query" placeholder="Search"
               value="{{ request.GET.query|default_if_none:'' }}">
        <button type="submit" class="col-3 btn btn-light mb-2">Search</button>

        <label class="sr-only" for="sort">Sort</label>
        <select class="form-control mb-2 mr-sm-2" id="sort" name="sort" onchange="this.form.submit()">
            {% if request.GET.sort == None %}
            <option disabled selected value style="display:none">Sort by: Featured</option>
            {% endif %}
            {% for value, name in sorting %}
            {% if request.GET.sort == value %}
            <option value="{{ value }}" selected>{{ name }}</option>
            {% else %}
            <option value="{{ value }}">{{ name }}</option>
            {% endif %}
            {% endfor %}
        </select>

        <label class="sr-only" for="type">Type</label>
        <select class="form-control mb-2 mr-sm-2" id="type" name="type" onchange="this.form.submit()">
            {% if request.GET.type == None %}
            <option disabled selected value style="display:none">Type</option>
            {% endif %}
            {% for value, name in types %}
            {% if value == request.GET.type|add:"0" %}
            <option value="{{ value }}" selected>{{ name }}</option>
            {% else %}
            <option value="{{ value }}">{{ name }}</option>
            {% endif %}
            {% endfor %}
        </select>

        <label class="sr-only" for="validity">Validity</label>
        <select class="form-control mb-2 mr-sm-2" id="validity" name="validity" onchange="this.form.submit()">
            {% if request.GET.validity == None %}
            <option disabled selected value style="display:none">Validity</option>
            {% endif %}
            {% for value, name in validities %}
            {% if value == request.GET.validity|add:"0" %}
            <option value="{{ value }}" selected>{{ name }}</option>
            {% else %}
            <option value="{{ value }}">{{ name }}</option>
            {% endif %}
            {% endfor %}
        </select>

        <label class="sr-only" for="company">Company</label>
        <select class="form-control mb-2 mr-sm-2" id="company" name="company" onchange="this.form.submit()">
            {% if request.GET.company == None %}
            <option disabled selected value style="display:none">Company</option>
            {% endif %}
            {% for value, name in companies %}
            {% if value == request.GET.company|add:"0" %}
            <option value="{{ value }}" selected>{{ name }}</option>
            {% else %}
            <option value="{{ value }}">{{ name }}</option>
            {% endif %}
            {% endfor %}
        </select>
    </form>
    <!-- Services -->
    {% if page_obj|length > 0 %}
    <h5 class="font-weight-bold">Found {{ found }} services</h5>
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Validity</th>
            <th scope="col">Type</th>
            <th scope="col">Price</th>
            <th scope="col">Company</th>
        </tr>
        </thead>
        <tbody>
        {% for service in page_obj %}
        <tr>
            <td><a href="{% url 'InsuranceApp:service' service.id %}">{{ service.title }}</a></td>
            <td>{{ service.validity.name }}</td>
            <td>{{ service.type.name }}</td>
            <td>${{ service.price|floatformat }}</td>
            <td>{{ service.company.name }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- Pagination -->
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?{% param_replace page=1 %}">&laquo; 1</a></li>
        <li class="page-item">
            <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a>
        </li>
        {% endif %}
        <li class="page-link text-dark">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">Next</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?{% param_replace page=page_obj.paginator.num_pages %}">
                {{ page_obj.paginator.num_pages }} &raquo;
            </a>
        </li>
        {% endif %}
    </ul>
    {% else %}
    <h4>There are no services at the moment</h4>
    {% endif %}
</div>
</body>
</html>

InsuranceApp/templates/login.html
<!DOCTYPE html>
{% load crispy_forms_tags %}

<!-- Header -->
{% include "_header.html" %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

<!-- Login -->
{% if user.is_authenticated %}
<div class="container py-5">
    <h3 class="text-center">You are logged in!</h3>
</div>
{% else %}
<div class="container py-5">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{ login_form|crispy }}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>
{% endif %}

<!-- Footer -->
{% include "_footer.html" %}
</body>
</html>

InsuranceApp/templates/mail.html
<h4>You have new response for «{{ service }}»</h4>
<table>
    <tbody>
    <tr>
        <td>Full name</td>
        <td>{{ full_name }}}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>{{ email }}</td>
    </tr>
    <tr>
        <td>Phone</td>
        <td>{{ phone }}</td>
    </tr>
    <tr>
        <td>Date</td>
        <td>{{ response_date|date }}</td>
    </tr>
    </tbody>
</table>

InsuranceApp/templates/register.html
<!DOCTYPE html>
{% load crispy_forms_tags %}

<!-- Header -->
{% include "_header.html" %}
<html lang="ru">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>

<!-- Register -->
{% if user.is_authenticated %}
<div class="container py-5">
    <h3 class="text-center">You are logged in!</h3>
</div>
{% else %}
<div class="container py-5">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        {{ register_form|crispy }}
        <button class="btn btn-primary" type="submit">Register</button>
    </form>
    <p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>
{% endif %}

<!-- Footer -->
{% include "_footer.html" %}
</body>
</html>

InsuranceApp/templates/responses.html
<!DOCTYPE html>
<!-- Header -->
{% include "_header.html" %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Responses</title>
</head>
<body>
<!--Responses-->
<div class="container py-5">
    {% if page_obj|length > 0 %}
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col">Birth Date</th>
            <th scope="col">Date</th>
            <th scope="col">Service</th>
        </tr>
        </thead>
        <tbody>
        {% for response in page_obj %}
        <tr>
            <td>{{ response.full_name }}</td>
            <td>{{ response.email }}</td>
            <td>{{ response.phone }}</td>
            <td>{{ response.birth_date }}</td>
            <td>{{ response.response_date }}</td>
            <td><a href="{% url 'InsuranceApp:service' response.service.id %}">{{ response.service.title }}</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- Pagination -->
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo; 1</a></li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% endif %}
        <li class="page-link text-dark">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                {{ page_obj.paginator.num_pages }} &raquo;
            </a>
        </li>
        {% endif %}
    </ul>
    {% else %}
    <h4>There are no responses at the moment</h4>
    {% endif %}
</div>
</body>
</html>

InsuranceApp/templates/service.html
<!DOCTYPE html>
{% load crispy_forms_tags %}

<!-- Header -->
{% include "_header.html" %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ service.title }}</title>
</head>
<body>
<div class="container py-5">
    <h4 class="font-weight-bold">{{ service.title }}</h4>
    {% if views != None %}
    <h6 class="text-muted">{{ views }} views</h6>
    {% endif %}
    <div class="row">
        <!-- Service info -->
        <div class="col-sm">
            <ul class="list-group">
                <li class="list-group-item">Company: {{ service.company.name }}</li>
                <li class="list-group-item">Price: ${{ service.price|floatformat }}</li>
                <li class="list-group-item">Coverage amount: ${{ service.coverage_amount|floatformat }}</li>
                <li class="list-group-item">Validity: {{ service.validity.name }}</li>
                <li class="list-group-item">Type: {{ service.type.name }}</li>
                <li class="list-group-item">Risks: {{ service.type.risks|join:", " }}</li>
                <li class="list-group-item">Description: {{ service.description }}</li>
            </ul>
        </div>
        <!-- Response form -->
        <div class="col-sm">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>
</body>
</html>